// Generated by CoffeeScript 1.9.3
(function() {
  this.Dimensions = (function() {
    function Dimensions(width, height) {
      this.vector = new Vector(width, height);
    }

    Dimensions.prototype.width = function() {
      return this.vector.x();
    };

    Dimensions.prototype.height = function() {
      return this.vector.y();
    };

    Dimensions.prototype.scaleToFit = function(other) {
      var newVec, ratio, ratio_x, ratio_y;
      ratio_x = other.width() / this.width();
      ratio_y = other.height() / this.height();
      ratio = ratio_x > ratio_y ? ratio_x : ratio_y;
      newVec = this.vector.scale(ratio);
      return new Dimensions(newVec.x(), newVec.y());
    };

    Dimensions.prototype.centerOffset = function(other) {
      var off_x, off_y;
      off_x = (other.width() - this.width()) / 2.0;
      off_y = (other.height() - this.height()) / 2.0;
      return new Vector(off_x, off_y);
    };

    return Dimensions;

  })();

}).call(this);
