// Generated by CoffeeScript 1.9.3
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  this.ImageBackground = (function(superClass) {
    extend(ImageBackground, superClass);

    function ImageBackground(url) {
      if (typeof url === 'string') {
        this.image = this.createImage(url);
      } else if (typeof url === 'object' && url instanceof Array) {
        this.image = this.createSrcSetImage(url);
      } else {
        throw "url provided to ImageBackground constructor must be string or array";
      }
    }

    ImageBackground.prototype.renderToCanvas = function(element, context, dTime) {
      var dims, imageDims, offset, scaledDims;
      if (dTime == null) {
        dTime = 0;
      }
      if (!this.ready) {
        return;
      }
      dims = this.getDimensions(element);
      imageDims = this.getDimensions(this.image);
      scaledDims = imageDims.scaleToFit(dims);
      offset = scaledDims.centerOffset(dims);
      return context.drawImage(this.image, offset.x(), offset.y(), scaledDims.width(), scaledDims.height());
    };

    ImageBackground.prototype.createSrcSetImage = function(values) {
      var img;
      img = document.createElement('img');
      img.addEventListener('load', (function(_this) {
        return function() {
          return _this.setReady();
        };
      })(this));
      if (this.isSrcsetSupported()) {
        img.srcset = values.join(' ');
      } else {
        img.src = values[0];
      }
      return img;
    };

    ImageBackground.prototype.createImage = function(url) {
      var img;
      img = document.createElement('img');
      img.addEventListener('load', (function(_this) {
        return function() {
          return _this.setReady();
        };
      })(this));
      img.src = url;
      return img;
    };

    ImageBackground.prototype.setReady = function() {
      this.ready = true;
      if (this.callback !== null) {
        return this.callback();
      }
    };

    ImageBackground.prototype.setCallback = function(fn) {
      return this.callback = fn;
    };

    ImageBackground.prototype.isSrcsetSupported = function() {
      var img;
      img = document.createElement('img');
      return typeof img.srcset === 'string';
    };

    return ImageBackground;

  })(this.BackgroundStrategy);

}).call(this);
